# -*- coding: utf-8 -*-
"""VRSE_DAY_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gl2vG1XWnnU3Ec77V22bWxkBBifSzGYl
"""



# Standar Input and Output

var_to_store = target_type(input())

num = int(input())

a = str(9.6)

print(a,type(a))

b = bool("")

print(b, type(b))

""
"Pavan"

age  = int(input("Enter Age : "))


if(age >= 18):
    print("Vote")
else:
    print("Can't")

num = 11

if(num == 0):
    print("ZERO")
elif(num % 2 == 0):
    print("EVEN")
else:
    print("ODD")

1750 // 500

1750 - 3*500

250 // 200

250 - 1*200

50 // 50

50 - 1*50

num = 3750

five = num // 500
num = num - five*500

two = num // 200
num = num - two*200

one = num // 100
num = num - one*100

fift = num  // 50
num = num - fift * 50

print(five)
print(two)
print(one)
print(fift)

amt = 0
u = 500

if(u > 300):
    amt += (u-300) * 8
    u = 300
if(u > 200):
    amt += (u-200) * 7
    u = 200
if(u > 100):
    amt += (u-100) * 6
    u = 100

amt += (u-0) * 5
u = 0

print(amt)



for i in range(5):
    for j in range(5):
        print(i,end=" ")
    print()

print("Hello",end=" ")
print(123)



n = 5
for i in range(n):
    for j in range(n):
        print("*",end=" ")
    print()

n = 5
for i in range(n):
    for j in range(n+4 ):
        print("*",end=" ")
    print()

def leftTriangle(n):
    for i in range(n):
        for j in range(i+1):
            print("*",end=" ")
        print()
leftTriangle(5)

def chrome(name = "Guest"):
    print("Welcome",name)
chrome()

def sayHello(name):
    print("Hello",name)
sayHello("Pavan")

def addAll(*args):
    print(args)
addAll(10,20,30,40,50)

s = "hello"

s[-4]

s = "hello"

# s[ : : ] --> [0:5:1]

# s[2: : ] --> [2:5:1]

# s[ :3: ] --> [0:3:1]

# s[ : : -1]

ord("0")











n = 5
for i in range(n):
    for k in range(i):
        print(" ",end=" ")
    for j in range(n-i):
        print("#",end=" ")
    print()

n = 7
for i in range(n):
    for k in range(n-i-1):
        print(" ",end=" ")
    for j in range(i+1):
        print("#",end=" ")
    print()

n = 5
x = 1
for i in range(n):
    for k in range(n-i-1):
        print(" ",end=" ")
    for j in range(x):
        print("#",end=" ")
    print()
    x += 2



# Input
n = 4
p = 5


# Output
dir = 1
per = 1
for i in range(p):
    per += dir
    if(per == n):
        dir = -1
print(per)

n = 20
for i in range(2,n):
    if(n % i == 0):
        print(i,end= " ")

for i in range(10):
    if(i== 3):
        continue
    print(i)

n = 13
flag = False;
for i in range(2,n):
    if(n % i == 0):
        flag = True
        break

if flag == True:
    print("Not Prime")
else:
    print("Prime")

num = 1024
sum = 0
while(num > 0):
    last = num % 10 # Extract Last Digit
    sum += last
    num = num // 10 # Remove the Extracted Digit to next Iteratoin
print(sum)

num = 1024
rev = 0
while(num > 0):
    last = num % 10
    rev = rev * 10 + last
    num = num // 10
print(rev)

# s = 'hello,world,how,are,you'
# .lower()--> convert to Lower case
# .upper()--> convert to Lower case
# s.capitalize() --> First letter Upeer case
# len(s) --> returns length of the string
# s.find("llo") --> returns the starting index of substring
# s.count("ll") --> returns the repeat count of the substring

# s.split(",") --> splits the text by seperator
# "-".join(lis) --> Joins the string with the seperator

# lis = ['hello', 'world', 'how', 'are', 'you']

s = "hello"

def countVowels(s):
    count = 0
    vow = 'aeiouAEIOU'
    for i in s:
        if i in vow:
            count+=1
    return count

res = countVowels("hello world how are you")
print(res)

def loop(n):
    for i in range(n):
        return i

x = loop(10)
print(x)



s = "hello"

for i in range(5):
    print(s[i])
print("-"*10)
for i in s:
    print(i)

#  COLLETCION in Python
# -->  list
# -->  tuple
# -->  set
# -->  dict



arr = [5,8,9,6,3,1,5,9,6,3]

# arr.append(100)
# arr.append(100)
# arr.append(100)

# print(arr.pop())

# arr.extend([90,100,200])


# arr.insert(1,200)

# print(arr.index(20))

arr.sort()

arr

# t = 1,

# t = tuple()

# t = 1,1,2


# print(type(t))


t = (1,2,3,4,5,6,7,8,9)



# print(t[0:3])

lis = []
for i in range(1,10+1):
    if(i % 2 == 0):
        lis.append(i)

print(lis)

# List

# List comphrension
def getEven(n):
    lis = []
    for i in range(1,n+1):
        if(i % 2 == 0 ):
            lis.append(i)
    return lis
res = getEven(20)
print(res)

lis = []
for i in range(1,21):
    if(i % 2 == 0):
        lis.append(i)
    else:
        lis.append(-1)
lis



[i if i % 2== 0 else -1 for i in range(1,21)]

d = dict()

# d['A'] = 1
# d['A']+=1

d['B'] = d.get('B',0)+1

d

def findMax(arr):
    mx = arr[0]
    for i in range(1,len(arr)):
        if(arr[i] > mx):
            mx = arr[i]
    return mx

res = findMax([10,2,999,1943,12,0])

res

def findMax(arr):
    mi = arr[0]
    for i in range(1,len(arr)):
        if(arr[i] < mi):
            mi = arr[i]
    return mi

res = findMax([10,2,999,1943,12,0])

res

arr = [5,15,10,6,14,7,9,15,15,14]
arr.sort()
arr

def findSecondMax(arr):
    arr.sort()
    for i in range(len(arr)-2,-1,-1):
        if(arr[i] != arr[i+1]):
            return arr[i]
    return -1

s = "listen"
t = "silent"

lis1 = list(s)
lis1.sort()

lis2 = list(t)
lis2.sort()

print(lis1)
print(lis2)

def isAnagram(s,t):
    if(len(s) != len(t)):
        return False
    freq = [0]*26
    for i in range(len(s)):
        sIdx = ord(s[i])-ord('a')
        freq[sIdx]+=1

        tIdx = ord(t[i])-ord('a')
        freq[tIdx]-=1

    for i in range(26):
        if(freq[i] != 0):
            return False
    return True

def removeDuplicates(arr):
    res = []
    for i in arr:
        if i not in res:
            res.append(i)
    return res

res = removeDuplicates([1,1,2,2,2,3,3,3,5,5,5,4])
print(res)

def findSingles(arr):
    freq = dict()
    for i in arr:
        if(freq.get(i) == None):
            freq[i] = 1
        else:
            freq[i] += 1
    res = []
    for i in freq.keys():
        if(freq[i] == 1):
            res.append(i)
    return res
res = findSingles([1,1,2,5,4,7,8,2,1,4,5,6,3,7])
print(res)

def sayHello():
    print("hello")
    sayHello()

sayHello()

freq = {
    1 : 1,
    20 : 2
}

# last = freq.get(20)
# freq[20] = last + 1

freq[20]+=1

print(freq[20])

def add(a,b):
    return a+b

res = add(10,20)
print(res)

add = lambda x,y : x+y

print(add(10,20))

lis = [
    (10,2),
    (1,2),
    (1,23),
    (2,0),
    (9,8),
    (10,15),
]
lis.sort(key=lambda x : x[0])
print(lis)

lis = [
    "pavan",
    "hello",
    "bye",
    "hii",
    "say",
    "hey"
]

lis.sort(key= lambda x : x[:2])

print(lis)

